create table if not exists public.visitor_logs (
    id bigint generated by default as identity primary key,
    collected_at timestamptz not null default now(),
    fb_url text,
    ip text,
    user_agent text,
    platform text,
    screen text,
    language text,
    timezone text
);

alter table public.visitor_logs enable row level security;

alter table public.visitor_logs
add column if not exists fb_url text;
